insert into category (category_name) values ('Breakfast');
insert into category (category_name) values ('Lunch');
insert into category (category_name) values ('Dinner');
insert into category (category_name) values ('Beverages');
insert into category (category_name) values ('Snacks');

insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Egg', 1, 100, '1no');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Bread slice with butter', 1, 90, '1no');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Chapati', 1, 60, '1no');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Puri', 1, 60, '1no');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Paratha', 1, 150, '1no');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Idli', 1, 100, '1no');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Dosa', 1, 120, '1no');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Sambhar', 1, 150, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Rice', 2, 130, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Curd', 2, 100, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Pickle', 2, 30, '1tsp');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Soup', 2, 75, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Papad', 2, 45, '1no');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Phulka', 3, 60, '1no');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Nan', 3, 150, '1no');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Dal', 3, 150, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Tea black with no sugar', 4, 10, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Coffee black with no sugar', 4, 10, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Tea with milk and sugar', 4, 45, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Coffee with milk and sugar', 4, 45, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Milk without sugar', 4, 10, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Milk with sugar', 4, 60, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Tea black with no sugar', 4, 75, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Fruit juice', 4, 120, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Soda', 4, 120, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Biscuit', 5, 30, '1no');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Fried Nuts', 5, 300, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Ice cream', 5, 200, '1cup');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Samosa', 5, 100, '1no');
insert into food (food_name, food_cat_id, cal_per_qty, units) values ('Cutlet', 5, 75, '1no');